### ISSUE TITLE
InspectContainerCommand fails to read JSON field "ArgsEscaped" into REST type ContainerConfiguration

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#104]
com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.ContainerConfiguration), not marked as ignorable (21 known properties: "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "Tty", "Cmd", "Labels", "AttachStdin", "AttachStderr", "HostConfig", "NetworkDisabled", "User", "OnBuild", "Domainname" [truncated]])
 at [Source: java.io.PushbackInputStream@1f1144c1; line: 1, column: 861] (through reference chain: com.alpha.pineapple.docker.model.rest.ImageInspect["ContainerConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfiguration["ArgsEscaped"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.ContainerConfiguration), not marked as ignorable (21 known properties: "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "Tty", "Cmd", "Labels", "AttachStdin", "AttachStderr", "HostConfig", "NetworkDisabled", "User", "OnBuild", "Domainname" [truncated]])
 at [Source: java.io.PushbackInputStream@1f1144c1; line: 1, column: 861] (through reference chain: com.alpha.pineapple.docker.model.rest.ImageInspect["ContainerConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfiguration["ArgsEscaped"]) 
    at com.alpha.pineapple.docker.DockerClientImpl.inspectImage(DockerClientImpl.java:447) 
    at com.alpha.pineapple.docker.command.ReportOnImagesCommand.inspectImage(ReportOnImagesCommand.java:203) 
    at com.alpha.pineapple.docker.command.ReportOnImagesCommand.execute(ReportOnImagesCommand.java:176) 
    at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88) 
    at com.alpha.pineapple.docker.DockerClientImpl.reportOnImages(DockerClientImpl.java:408)

**Comment by athrane** [comment]
Closed with commit  04f43db.
