### ISSUE TITLE
InspectContainerCommand fails to read JSON field "ArgsEscaped" into REST type InspectedImageConfiguration

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#105]
<2017-04-30 22:13:43,586> <DEBUG> <ExecutionResultImpl> <Message added with id [Stack Trace] and content [com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.InspectedImageConfiguration), not marked as ignorable (23 known properties: "VolumeDriver", "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "Tty", "Cmd", "Labels", "AttachStdin", "AttachStderr", "NetworkDisabled", "User", "OnBuild", "Domainname" [truncated]])
 at [Source: java.io.PushbackInputStream@433defed; line: 1, column: 1582] (through reference chain: com.alpha.pineapple.docker.model.rest.ImageInspect["Config"]->com.alpha.pineapple.docker.model.rest.InspectedImageConfiguration["ArgsEscaped"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.InspectedImageConfiguration), not marked as ignorable (23 known properties: "VolumeDriver", "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "Tty", "Cmd", "Labels", "AttachStdin", "AttachStderr", "NetworkDisabled", "User", "OnBuild", "Domainname" [truncated]])
 at [Source: java.io.PushbackInputStream@433defed; line: 1, column: 1582] (through reference chain: com.alpha.pineapple.docker.model.rest.ImageInspect["Config"]->com.alpha.pineapple.docker.model.rest.InspectedImageConfiguration["ArgsEscaped"])
	at com.alpha.pineapple.docker.DockerClientImpl.inspectImage(DockerClientImpl.java:447)
	at com.alpha.pineapple.docker.command.ReportOnImagesCommand.inspectImage(ReportOnImagesCommand.java:203)
	at com.alpha.pineapple.docker.command.ReportOnImagesCommand.execute(ReportOnImagesCommand.java:176)
	at com.alpha.pineapple.docker.command.ReportOnImagesCommandSystemTest.testCommandCanReportOnImages(ReportOnImagesCommandSystemTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)

**Comment by athrane** [comment]
The schema type is inspectedImageConfigurationType replaced with containerConfigurationType as defined in https://github.com/moby/moby/blob/04295d26df3034a9a92da8400418f843d7c48780/api/types/types.go:

type ImageInspect struct {
	ContainerConfig *container.Config
	Config          *container.Config
