### ISSUE TITLE
Fails to handle error messages when creating image from unknown repository

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#106]
com.alpha.pineapple.docker.utils.RestResponseException: Docker host reported error: {"message":"repository ftdpegnorf not found: does not exist or no pull access"}
. Reported status code:404
	at com.alpha.pineapple.docker.utils.RestResponseErrorHandler.handleError(RestResponseErrorHandler.java:68)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:347)
	at com.alpha.pineapple.docker.session.DockerSessionImpl.httpPostForObjectWithMultipleRootElements(DockerSessionImpl.java:292)
	at com.alpha.pineapple.docker.session.DockerSessionImpl.httpPostForObjectWithMultipleRootElements(DockerSessionImpl.java:277)
	at com.alpha.pineapple.docker.command.CreateImageCommand.execute(CreateImageCommand.java:198)
	at com.alpha.pineapple.docker.command.CreateImageCommandSystemTest.testFailsToCreateImageFromUnknownRepository(CreateImageCommandSystemTest.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by athrane** [comment]
Is the imageCreationType used anymore? Doesn't seem to be defined in the v1.28 API: https://docs.docker.com/engine/api/v1.28/#operation/ImageCreate
