### ISSUE TITLE
Fails to inspect containers with exception:  Unrecognized field "ArgsEscaped" in InspectedContainerConfiguration

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#107]
com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.InspectedContainerConfiguration), not marked as ignorable (25 known properties: "VolumeDriver", "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "MemorySwap", "Tty", "Cmd", "Labels", "Memory", "AttachStdin", "AttachStderr", "NetworkDisabled", "User" [truncated]])
at [Source: java.io.PushbackInputStream@6771de17; line: 1, column: 3273] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJsonBase["Config"]->com.alpha.pineapple.docker.model.rest.InspectedContainerConfiguration["ArgsEscaped"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ArgsEscaped" (class com.alpha.pineapple.docker.model.rest.InspectedContainerConfiguration), not marked as ignorable (25 known properties: "VolumeDriver", "MacAddress", "StdinOnce", "Env", "AttachStdout", "Hostname", "MemorySwap", "Tty", "Cmd", "Labels", "Memory", "AttachStdin", "AttachStderr", "NetworkDisabled", "User" [truncated]])
at [Source: java.io.PushbackInputStream@6771de17; line: 1, column: 3273] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJsonBase["Config"]->com.alpha.pineapple.docker.model.rest.InspectedContainerConfiguration["ArgsEscaped"])
at com.alpha.pineapple.docker.DockerClientImpl.inspectContainer(DockerClientImpl.java:821)
at com.alpha.pineapple.docker.command.ReportOnContainersCommand.inspectContainer(ReportOnContainersCommand.java:206)
at com.alpha.pineapple.docker.command.ReportOnContainersCommand.execute(ReportOnContainersCommand.java:178)
at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88)
at com.alpha.pineapple.docker.DockerClientImpl.reportOnContainers(DockerClientImpl.java:842)
at com.alpha.pineapple.plugin.docker.operation.CreateReport.reportOnContainers(CreateReport.java:147)
at com.alpha.pineapple.plugin.docker.operation.CreateReport.createReport(CreateReport.java:123)
at com.alpha.pineapple.plugin.docker.operation.CreateReport.execute(CreateReport.java:102)

**Comment by athrane** [comment]
Closed with commit  fd29734 as part of issue #112
