### ISSUE TITLE
Building Artifactory container for Pineapple CI setup fails with NullPointerException

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#120]
com.alpha.pineapple.plugin.PluginExecutionFailedException: Operation failed with exception: java.lang.NullPointerException. Operation execution is aborted. 
    at com.alpha.pineapple.plugin.docker.operation.DeployConfiguration.execute(DeployConfiguration.java:134) 
    at com.alpha.pineapple.plugin.session.RetrySessionHandlerImpl.execute(RetrySessionHandlerImpl.java:123) 
    at com.alpha.pineapple.command.InvokePluginsCommand.excuteWithPlugin(InvokePluginsCommand.java:399) 
    at com.alpha.pineapple.command.InvokePluginsCommand.executeModel(InvokePluginsCommand.java:355) 
    at com.alpha.pineapple.command.InvokePluginsCommand.executeModels(InvokePluginsCommand.java:270) 
    at com.alpha.pineapple.command.InvokePluginsCommand.execute(InvokePluginsCommand.java:228) 
    at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88) 
    at com.alpha.pineapple.execution.OperationTaskImpl.invokePlugins(OperationTaskImpl.java:391) 
    at com.alpha.pineapple.execution.OperationTaskImpl.executeWithRegisteredContext(OperationTaskImpl.java:215) 
    at com.alpha.pineapple.execution.OperationTaskImpl.execute(OperationTaskImpl.java:133) 
    at com.alpha.pineapple.execution.AsyncOperationTaskImpl.execute(AsyncOperationTaskImpl.java:56) 
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
    at java.lang.reflect.Method.invoke(Unknown Source) 
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) 
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) 
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) 
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:110) 
    at java.util.concurrent.FutureTask.run(Unknown Source) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
    at java.lang.Thread.run(Unknown Source) 
Caused by: java.lang.NullPointerException 
    at **com.alpha.pineapple.plugin.docker.model.MapperImpl.mapContainerProperties(MapperImpl.java:403)** 
    at com.alpha.pineapple.plugin.docker.model.MapperImpl.mapContainerForCreation(MapperImpl.java:144) 
    at com.alpha.pineapple.plugin.docker.operation.DeployConfiguration.createContainer(DeployConfiguration.java:277) 
    at com.alpha.pineapple.plugin.docker.operation.DeployConfiguration.processModel(DeployConfiguration.java:178) 
    at com.alpha.pineapple.plugin.docker.operation.DeployConfiguration.execute(DeployConfiguration.java:127) 
    ... 22 more

**Comment by athrane** [comment]
Failed due to missing initialization of host configuration in target model
