### ISSUE TITLE
Failure to start web application due to ZK exception: Class not found: org.zkoss.zkex.ui.comet.CometServerPush

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#148]
WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@7eb6b6b6{/,file:/C:/Users/AllanThrane/git/pineapple/applications/pineapple-web-application/pineapple-web-application-war/src/main/webapp/,STARTING}{file:/C:/Users/AllanThrane/git/pineapple/applications/pineapple-web-application/pineapple-web-application-war/src/main/webapp/}
org.zkoss.zk.ui.UiException: Class not found: org.zkoss.zkex.ui.comet.CometServerPush
	at org.zkoss.zk.device.Devices$DeviceInfo.getServerPushClass(Devices.java:483)
	at org.zkoss.zk.device.GenericDevice.init(GenericDevice.java:128)
	at org.zkoss.zk.device.Devices$DeviceInfo.newDevice(Devices.java:511)
	at org.zkoss.zk.device.Devices$DeviceInfo.access$000(Devices.java:424)
	at org.zkoss.zk.device.Devices.getDevice(Devices.java:72)
	at org.zkoss.zk.ui.metainfo.DefinitionLoaders.parseLang(DefinitionLoaders.java:280)
	at org.zkoss.zk.ui.metainfo.DefinitionLoaders.load0(DefinitionLoaders.java:179)
	at org.zkoss.zk.ui.metainfo.DefinitionLoaders.load(DefinitionLoaders.java:155)
	at org.zkoss.zk.ui.metainfo.LanguageDefinition.init(LanguageDefinition.java:316)
	at org.zkoss.zk.ui.metainfo.LanguageDefinition.getAll(LanguageDefinition.java:295)
	at org.zkoss.zk.ui.http.WebManager.getCWRURLPrefix(WebManager.java:273)

**Comment by athrane** [comment]
Se ZK compoent definitions here: https://www.zkoss.org/wiki/ZK%20Installation%20Guide/ZK%20Background/The%20Content%20of%20ZK%20Binary%20Distribution

**Comment by athrane** [comment]
Solution is to add dependency to zkex:

<dependency>
	<groupId>org.zkoss.zk</groupId>
	<artifactId>zkex</artifactId>
	<version>${zk.version}</version>				
</dependency>			    		


due to the usage of 

<server-push-class>org.zkoss.zkex.ui.comet.CometServerPush</server-push-class>						

in zk.xml.
