### ISSUE TITLE
Failure to inspect exposed container ports

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#152]
The error can be observed in the testcase StartContainerCommandSystemTest.testCommandStartContainerDockerRegistry(..).

**Stacktrace:**

com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@33e3bd2e; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@33e3bd2e; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"])
	at com.alpha.pineapple.docker.DockerClientImpl.inspectContainer(DockerClientImpl.java:821)
	at com.alpha.pineapple.docker.DockerClientImpl.isContainerRunning(DockerClientImpl.java:893)
	at com.alpha.pineapple.docker.command.StartContainerCommandSystemTest.testCommandStartContainerDockerRegistry(StartContainerCommandSystemTest.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

com.alpha.testutils.DockerTestHelperException: Failed to stop container with error: Could not read JSON: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@18a98913; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@18a98913; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"])
	at com.alpha.testutils.DockerTestHelper.stopContainer(DockerTestHelper.java:594)
	at com.alpha.pineapple.docker.command.StartContainerCommandSystemTest.tearDown(StartContainerCommandSystemTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@18a98913; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "5000/tcp" (class com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts), not marked as ignorable (one known property: "Port"])
 at [Source: java.io.ByteArrayInputStream@18a98913; line: 1, column: 3719] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["NetworkSettings"]->com.alpha.pineapple.docker.model.rest.InspectedContainerNetworkSettings["Ports"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationExposedPorts["5000/tcp"])
	at com.alpha.pineapple.docker.DockerClientImpl.stopContainer(DockerClientImpl.java:655)
	at com.alpha.testutils.DockerTestHelper.stopContainer(DockerTestHelper.java:588)
	... 29 more

**Comment by athrane** [comment]
**Docker types**

1.1)
Docker type for container inspection is ContainerJson (https://github.com/moby/moby/blob/master/api/types/types.go)

1.2) 
ContainerJson type contains network settings:
```
type ContainerJSON struct {
	*ContainerJSONBase
	Mounts          []MountPoint
	Config          *container.Config
	NetworkSettings *NetworkSettings
}
```

1.3) 
Docker NetworkSettings type (https://github.com/moby/moby/blob/master/api/types/types.go#L342) : 
```
type NetworkSettings struct {
	NetworkSettingsBase
	DefaultNetworkSettings
	Networks map[string]*network.EndpointSettings
}
```

1.4) Docker NetworkSettingsBase defines ports:
```
type NetworkSettingsBase struct {
        ....
	Ports                  nat.PortMap // Ports is a collection of PortBinding indexed by Port
}
```

1.5) Docker nat.PortMap is defined in the docker/go-connections repository (https://github.com/docker/go-connections/):

```
type PortMap map[Port][]PortBinding

// Port is a string containing port number and protocol in the format "80/tcp"
type Port string

```
**Pineapple schema**

2.1) Used schema type for container inspection is containerJsonType.
2.3) Used schema type is network settings is inspectedContainerNetworkSettingsType
2.4) inspectedContainerNetworkSettingsType contains ports implemented by the  containerConfigurationExposedPortsType:
```
	<xs:complexType name="inspectedContainerNetworkSettingsType" >
		<xs:annotation>
			<xs:documentation>Info about the network configuration of a Docker container (Partial output from inspecting a container).</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ports" type="containerConfigurationExposedPortsType" minOccurs="0" maxOccurs="1" />
```
2.5)
