### ISSUE TITLE
Testcase ReportOnContainersCommandSystemTest.testCommandCanReportOnContainers fails with: IllegalArgumentException: targetObject is undefined

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#155]
Stack trace:
```
<2017-06-17 17:09:00,218> <DEBUG> <ExecutionResultImpl> <Message added with id [Error Message] and content [Could not read JSON: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"])].>
<2017-06-17 17:09:00,219> <DEBUG> <ExecutionResultImpl> <Message added with id [Stack Trace] and content [org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:252)
```

**Comment by athrane** [comment]
Addition stack trace:

```
<2017-06-17 17:09:00,218> <DEBUG> <ExecutionResultImpl> <Message added with id [Error Message] and content [Could not read JSON: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"])].>
<2017-06-17 17:09:00,219> <DEBUG> <ExecutionResultImpl> <Message added with id [Stack Trace] and content [org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@45c8d09f; line: 1, column: 2149] (through reference chain: com.alpha.pineapple.docker.model.rest.ContainerJson["HostConfig"]->com.alpha.pineapple.docker.model.rest.ContainerConfigurationHostConfig["Devices"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:252)

```
