### ISSUE TITLE
Starting web application fails with NullPointerException in ConfigurationController

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#192]
## Stacktrace: 

```
	... 26 more
Caused by: org.zkoss.zk.ui.UiException
	at org.zkoss.bind.impl.AbstractAnnotatedMethodInvoker.invokeMethod(AbstractAnnotatedMethodInvoker.java:93)
	at org.zkoss.bind.impl.BinderImpl.init(BinderImpl.java:339)
	at org.zkoss.bind.AnnotateBinder.init(AnnotateBinder.java:57)
	at org.zkoss.bind.BindComposer.doBeforeComposeChildren(BindComposer.java:159)
	... 90 more
Caused by: java.lang.NullPointerException
	at com.alpha.pineapple.web.spring.rest.ConfigurationController.getCredentialConfiguration(ConfigurationController.java:708)
	at com.alpha.pineapple.web.zk.viewmodel.EnvironmentConfigurationPanel.addCredentialsToModel(EnvironmentConfigurationPanel.java:438)
	at com.alpha.pineapple.web.zk.viewmodel.EnvironmentConfigurationPanel.createViewModel(EnvironmentConfigurationPanel.java:384)
	at com.alpha.pineapple.web.zk.viewmodel.EnvironmentConfigurationPanel.init(EnvironmentConfigurationPanel.java:343)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.zkoss.bind.impl.ParamCall.call(ParamCall.java:113)
	at org.zkoss.bind.impl.AbstractAnnotatedMethodInvoker.invokeMethod(AbstractAnnotatedMethodInvoker.java:88)
	... 93 more
```

## Failed code: 
```
    public Configuration getCredentialConfiguration() {

	// get credential provider and create credential
	Administration admin = coreComponent.getAdministration();
	CredentialProvider provider = admin.getCredentialProvider();

	// get credential configuration
	com.alpha.pineapple.credential.EnvironmentInfo[] environmentInfos = provider.getEnvironments();

	// map to model
	return restResultMapper.mapCredentialConfiguration(environmentInfos);
}
```

## Logs output shows failed core initialization due to missing plugin:
```
<2018-03-18 21:46:24,395> <DEBUG> <ResultRepositoryImpl> <State change notification to [EXECUTING] for execution result [Initialize plugin com.alpha.pineapple.plugin.fusion.installation ]. >
<2018-03-18 21:46:24,395> <DEBUG> <PluginCandidateScannerImpl> <Starting to resolve class loader for plugin id: com.alpha.pineapple.plugin.fusion.installation.>
<2018-03-18 21:46:24,396> <DEBUG> <PluginCandidateScannerImpl> <Class loader resolution returned resource(s): java.util.Collections$3@6ffdbe66[i=java.util.ArrayList$Itr@40259b7e].>
<2018-03-18 21:46:24,397> <DEBUG> <PluginCandidateScannerImpl> <Successfully completed scan for plugins.>
<2018-03-18 21:46:24,399> <DEBUG> <ExecutionResultImpl> <Message added with id [Error Message] and content [Failed to initialize plugin, since plugin package [com.alpha.pineapple.plugin.fusion.installation] didnt contain a plugin class annotated with @Plugin.].>
<2018-03-18 21:46:24,400> <DEBUG> <ExecutionResultImpl> <State is set to [FAILURE] for [Initialize plugin com.alpha.pineapple.plugin.fusion.installation ].>
<2018-03-18 21:46:24,400> <DEBUG> <ResultRepositoryImpl> <State change notification to [FAILURE] for execution result [Initialize plugin com.alpha.pineapple.plugin.fusion.installation ]. >
<2018-03-18 21:46:24,400> <DEBUG> <ExecutionResultImpl> <Message added with id [Message] and content [Successfully initialized plugin repository.].>
<2018-03-18 21:46:24,400> <DEBUG> <ExecutionResultImpl> <State is set to [COMPUTED] for [Initialize plugin repository.].>
<2018-03-18 21:46:24,401> <DEBUG> <ExecutionResultImpl> <Message added with id [Composite Execution Result] and content [Results: 8, successful: 4, failures: 4, errors: 0, interrupted: 0.].>
<2018-03-18 21:46:24,401> <DEBUG> <ExecutionResultImpl> <State is computed to [FAILURE].>
<2018-03-18 21:46:24,401> <DEBUG> <ResultRepositoryImpl> <State change notification to [FAILURE] for execution result [Initialize plugin repository.]. >
<2018-03-18 21:46:24,401> <DEBUG> <PluginRepositoryImpl> <Successfully initialized plugin repository.>
<2018-03-18 21:46:24,401> <DEBUG> <ExecutionResultImpl> <State is set to [COMPUTED] for [Plugin activator initialization].>
<2018-03-18 21:46:24,401> <DEBUG> <ExecutionResultImpl> <Message added with id [Composite Execution Result] and content [Results: 1, successful: 0, failures: 1, errors: 0, interrupted: 0.].>
<2018-03-18 21:46:24,401> <DEBUG> <ExecutionResultImpl> <State is computed to [FAILURE].>
<2018-03-18 21:46:24,401> <DEBUG> <ResultRepositoryImpl> <State change notification to [FAILURE] for execution result [Plugin activator initialization]. >
<2018-03-18 21:46:24,402> <DEBUG> <ExecutionResultImpl> <Message added with id [Message] and content [Initialization failed, because [1] child executions failed and [0] child executions terminated with an error.].>
<2018-03-18 21:46:24,402> <DEBUG> <ExecutionResultImpl> <State is set to [COMPUTED] for [Pineapple core component initialization.].>
<2018-03-18 21:46:24,402> <DEBUG> <ExecutionResultImpl> <Message added with id [Composite Execution Result] and content [Results: 4, successful: 3, failures: 1, errors: 0, interrupted: 0.].>
<2018-03-18 21:46:24,402> <DEBUG> <ExecutionResultImpl> <State is computed to [FAILURE].>
<2018-03-18 21:46:24,403> <DEBUG> <ResultRepositoryImpl> <State change notification to [FAILURE] for execution result [Pineapple core component initialization.]. >
```

## Solutions
One solution is #193.
Another solution is to remove the missing component from the default configuration.

**Comment by athrane** [comment]
Resolved through removal of deprecated plugins from default configuration. 
Definition of resources using non-existing resources triggers resolution of plugins which resulted in the failure. #193 should be implemented to make plugin resolution more robust.
