### ISSUE TITLE
Core component fails to initialize due to error: NoClassDefFoundError: javax/activation/DataSource

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#198]
## Stacktrace:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alpha.pineapple.PineappleCore]: Factory method 'createCore' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/activation/DataSource
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 31 more
Caused by: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:478)
	at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:63)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:128)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:162)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:92)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:455)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:289)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:217)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:175)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:353)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:508)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:465)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:366)
	at com.alpha.pineapple.command.MarshallJAXBObjectsCommand.doMarshall(MarshallJAXBObjectsCommand.java:196)
	at com.alpha.pineapple.command.MarshallJAXBObjectsCommand.execute(MarshallJAXBObjectsCommand.java:150)
	at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88)
	at com.alpha.pineapple.command.CommandFacadeImpl.marshallJaxbObjects(CommandFacadeImpl.java:134)
	at com.alpha.pineapple.command.CommandFacadeImpl.saveJaxbObjects(CommandFacadeImpl.java:146)
	at com.alpha.pineapple.command.CreateDefaultEnvironmentConfigurationCommand.execute(CreateDefaultEnvironmentConfigurationCommand.java:247)
	at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88)
	at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:74)
	at com.alpha.pineapple.CoreImpl.createDefaultConfiguration(CoreImpl.java:375)
	at com.alpha.pineapple.CoreImpl.initialize(CoreImpl.java:279)
	at com.alpha.pineapple.CoreFactory.createCore(CoreFactory.java:116)
	at com.alpha.pineapple.web.WebAppCoreFactory.createCore(WebAppCoreFactory.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 32 more
```

## Solution
Add dependency to the JavaBeans Activation Framework (JAF):

```
<dependency>
    <groupId>com.sun.activation</groupId>
    <artifactId>javax.activation</artifactId>
    <version>1.2.0</version>
</dependency>
```

https://stackoverflow.com/questions/46493613/what-is-the-replacement-for-javax-activation-package-in-java-9/46493809#46493809

**Comment by athrane** [comment]
Closed with commit 040336a29f90b18471cdf7ed06a554b123a55b69.
