### ISSUE TITLE
Unit test of CredentialConfigurationMarshallerImpl.save() fails with: SaveConfigurationFailedException: Failed to save credentials configuration: null

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#199]
## Stacktrace:
```
com.alpha.pineapple.credential.SaveConfigurationFailedException: Failed to save credentials configuration: null
	at com.alpha.pineapple.credential.CredentialConfigurationMarshallerImpl.save(CredentialConfigurationMarshallerImpl.java:103)
	at com.alpha.pineapple.credential.encryption.PasswordEncryptingCredentialConfigurationMarshallerImpl.save(PasswordEncryptingCredentialConfigurationMarshallerImpl.java:89)
	at com.alpha.pineapple.credential.FileBasedCredentialProviderImpl.saveProvider(FileBasedCredentialProviderImpl.java:417)
	at com.alpha.pineapple.credential.FileBasedCredentialProviderImpl.initialize(FileBasedCredentialProviderImpl.java:139)
	at com.alpha.pineapple.CoreFactory.createCredentialProvider(CoreFactory.java:264)
	at com.alpha.testutils.ObjectMotherCredentialProvider.createEmptyCredentialProvider(ObjectMotherCredentialProvider.java:80)
	at com.alpha.pineapple.CredentialProviderIntegrationTest.setUp(CredentialProviderIntegrationTest.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

## Log output:
```
<2018-03-22 18:54:55,751> <DEBUG> <DirectoryTestExecutionListener> <Initialized test directory <C:\Users\Thrane\AppData\Local\Temp\testcases\CredentialProviderIntegrationTest-testCanCreateCredentialProviderFromFactory> for method <CredentialProviderIntegrationTest.testCanCreateCredentialProviderFromFactory(..)>.>
<2018-03-22 18:54:55,751> <DEBUG> <MarshallJAXBObjectsCommand> <Starting to save JAXB objects.>
<2018-03-22 18:54:55,767> <DEBUG> <MarshallJAXBObjectsCommand> <Will save objects to file [C:\Users\Thrane\git\pineapple\modules\pineapple-core\Documents and Settings\Thrane\.pineapple\conf\credentials.xml] using Java package [com.alpha.pineapple.model.configuration].>
<2018-03-22 18:54:55,767> <DEBUG> <ExecutionResultImpl> <Message added with id [Error Message] and content [Failed to save objects due path not being absolute: C:\Users\Thrane\git\pineapple\modules\pineapple-core\Documents and Settings\Thrane\.pineapple\conf].>
<2018-03-22 18:54:55,767> <DEBUG> <ExecutionResultImpl> <State is set to [FAILURE] for [Save file: C:\Users\Thrane\git\pineapple\modules\pineapple-core\Documents and Settings\Thrane\.pineapple\conf\credentials.xml].>

```

**Comment by athrane** [comment]
Solution is to remove validation of whether path is absolute in MarshallJAXBObjectsCommand. Closed with commit be5c2f2c6a8feb1f8a9dd8c7920355a4c70da49f.
