### ISSUE TITLE
mvn jetty:run fails with RuntimeException: Error scanning entry META-INF/versions/9/...

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#228]
Stacktrace:

```
[INFO] jetty-9.2.3.v20140905
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@4a23350{/,file:/C:/Users/Thrane/git/pineapple/applications/pineapple-web-application/pineapple-web-application-war/src/main/webapp/,STARTING}{file:/C:/Users/Thrane/git/pineapple/applications/pineapple-web-application/pineapple-web-application-war/src/main/webapp/}
MultiException[java.lang.RuntimeException: Error scanning entry META-INF/versions/9/javax/xml/bind/ModuleUtil.class from jar file:/C:/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/C:/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar]
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:535)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:446)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:471)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1329)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:365)

```

**Comment by athrane** [comment]
Resolved by commit acb3239e65d47fe95f1dfdd0556260b3e1f55d71.
