### ISSUE TITLE
pineapple-ci-module fails to to build Jenkins container

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#58]
Module name is: xx-pineapple-dev-docker-install-ci-linux64
Stack trace:
	
Plugin execution failed with the error: Operation failed with exception: com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"]). Operation execution is aborted.

**Comment by athrane** [comment]
Stack trace 2:
<2017-04-14 17:27:10,339> <DEBUG> <DockerSessionImpl> <Invoking URL: http://192.168.99.10:8082/images/json?all=true>
<2017-04-14 17:27:10,483> <DEBUG> <ExecutionResultImpl> <Message added with id [Error Message] and content [Could not read JSON: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"])].>
<2017-04-14 17:27:10,491> <DEBUG> <ExecutionResultImpl> <Message added with id [Stack Trace] and content [org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Containers" (class com.alpha.pineapple.docker.model.rest.ListedImage), not marked as ignorable (8 known properties: "Size", "ParentId", "Created", "RepoTags", "Id", "VirtualSize", "RepoDigests", "Labels"])
 at [Source: java.io.PushbackInputStream@338462f3; line: 1, column: 18] (through reference chain: com.alpha.pineapple.docker.model.rest.ListedImage["Containers"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:252)
	at com.alpha.pineapple.docker.session.DockerSessionImpl.httpGetForObject(DockerSessionImpl.java:318)
	at com.alpha.pineapple.docker.command.ListAllImagesCommand.execute(ListAllImagesCommand.java:137)
	at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88)
	at com.alpha.pineapple.docker.DockerClientImpl.listImages(DockerClientImpl.java:383)
	at com.alpha.pineapple.docker.DockerClientImpl.imageExists(DockerClientImpl.java:217)
	at com.alpha.pineapple.docker.command.BuildImageCommand.buildImage(BuildImageCommand.java:245)
	at com.alpha.pineapple.docker.command.BuildImageCommand.execute(BuildImageCommand.java:227)
	at com.alpha.pineapple.command.execution.CommandRunnerImpl.run(CommandRunnerImpl.java:88)
	at com.alpha.pineapple.docker.DockerClientImpl.buildImage(DockerClientImpl.java:298)
	at com.alpha.pineapple.plugin.docker.operation.DeployConfiguration.buildImageFromDockerfile(DeployConfiguration.java:256)

**Comment by athrane** [comment]
Fixed with commit 56c2fab.
