### ISSUE TITLE
InspectImageCommand fails to read JSON GraphDriver "Data" field

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#63]
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "RootDir" (class com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData), not marked as ignorable (3 known properties: "DeviceId", "DeviceName", "DeviceSize"])
 at [Source: java.io.PushbackInputStream@1caa0244; line: 1, column: 1783] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedImage["GraphDriver"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriver["Data"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData["RootDir"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "RootDir" (class com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData), not marked as ignorable (3 known properties: "DeviceId", "DeviceName", "DeviceSize"])
 at [Source: java.io.PushbackInputStream@1caa0244; line: 1, column: 1783] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedImage["GraphDriver"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriver["Data"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData["RootDir"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:252)
	at com.alpha.pineapple.docker.session.DockerSessionImpl.httpGetForObject(DockerSessionImpl.java:318)
	at com.alpha.pineapple.docker.command.InspectImageCommand.execute(InspectImageCommand.java:156)
	at com.alpha.pineapple.docker.command.InspectImageCommandSystemTest.testCommandCanInspectImage(InspectImageCommandSystemTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "RootDir" (class com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData), not marked as ignorable (3 known properties: "DeviceId", "DeviceName", "DeviceSize"])
 at [Source: java.io.PushbackInputStream@1caa0244; line: 1, column: 1783] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedImage["GraphDriver"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriver["Data"]->com.alpha.pineapple.docker.model.rest.InspectedImageGraphDriverData["RootDir"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:671)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:762)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1275)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2158)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:205)
	... 39 more

**Comment by athrane** [comment]
Current version of the schema for the REST model defines:
	<xs:complexType name="inspectedImageGraphDriverDataType" >
		<xs:annotation>
			<xs:documentation>Docker image graph driver data configuration (Output from inspecting an image).</xs:documentation>
		</xs:annotation>
		<xs:attribute name="deviceId" type="xs:string" use="optional"/>		
		<xs:attribute name="deviceName" type="xs:string" use="optional"/>		
		<xs:attribute name="deviceSize" type="xs:string" use="optional"/>				
	</xs:complexType>

Docker defines the type GraphDriverData at: 
https://github.com/docker/docker/blob/a69c4129e086e4e7b86cce7d2682685dfdc6f2d2/api/types/graph_driver_data.go
https://github.com/docker/docker/blob/04295d26df3034a9a92da8400418f843d7c48780/api/types/types.go
