### ISSUE TITLE
InspectContainerCommand fails to read JSON field "OomScoreAdj" into REST type InspectedContainerHostConfig

### ISSUE THREAD

**Issue by athrane** [athrane/pineapple#70]
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@33ecda92; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@33ecda92; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:208)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:200)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:97)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:252)
	at com.alpha.pineapple.docker.session.DockerSessionImpl.httpGetForObject(DockerSessionImpl.java:318)
	at com.alpha.pineapple.docker.command.InspectContainerCommand.execute(InspectContainerCommand.java:159)
	at com.alpha.pineapple.docker.command.InspectContainerCommandSystemTest.testCanInspectContainer(InspectContainerCommandSystemTest.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@33ecda92; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:671)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:762)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1275)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2158)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:205)
	... 39 more

com.alpha.testutils.DockerTestHelperException: Failed to stop container with error: Could not read JSON: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@5884a914; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@5884a914; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"])
	at com.alpha.testutils.DockerTestHelper.stopContainer(DockerTestHelper.java:594)
	at com.alpha.pineapple.docker.command.InspectContainerCommandSystemTest.tearDown(InspectContainerCommandSystemTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.alpha.pineapple.docker.DockerClientException: Could not read JSON: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@5884a914; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "OomScoreAdj" (class com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig), not marked as ignorable (43 known properties: "PublishAllPorts", "RestartPolicy", "CapDrop", "GroupAdd", "VolumeDriver", "VolumesFrom", "CpusetCpus", "LogConfig", "Dns", "PortBindings", "CapAdd", "CpuQuota", "DnsSearch", "NetworkMode" [truncated]])
 at [Source: java.io.PushbackInputStream@5884a914; line: 1, column: 1039] (through reference chain: com.alpha.pineapple.docker.model.rest.InspectedContainer["HostConfig"]->com.alpha.pineapple.docker.model.rest.InspectedContainerHostConfig["OomScoreAdj"])
	at com.alpha.pineapple.docker.DockerClientImpl.stopContainer(DockerClientImpl.java:655)
	at com.alpha.testutils.DockerTestHelper.stopContainer(DockerTestHelper.java:588)
	... 29 more

**Comment by athrane** [comment]
Remote API documentation v1.28 (https://docs.docker.com/engine/api/v1.28/#operation/ContainerInspect) states required type is: HostConfig.OomScoreAdj (integer)

Defined Docker type (https://github.com/moby/moby/blob/04295d26df3034a9a92da8400418f843d7c48780/api/types/types.go):

// ContainerJSONBase contains response of Engine API:
// GET "/containers/{name:.*}/json"
type ContainerJSONBase struct {
        // ....
	HostConfig      *container.HostConfig
}

https://github.com/moby/moby/blob/04295d26df3034a9a92da8400418f843d7c48780/api/types/container/host_config.go:

// HostConfig the non-portable Config structure of a container.
// Here, "non-portable" means "dependent of the host we are running on".
// Portable information *should* appear in Config.
type HostConfig struct {
	// Applicable to all platforms
	Binds           []string      // List of volume bindings for this container
	ContainerIDFile string        // File (path) where the containerId is written
	LogConfig       LogConfig     // Configuration of the logs for this container
	NetworkMode     NetworkMode   // Network mode to use for the container
	PortBindings    nat.PortMap   // Port mapping between the exposed port (container) and the host
	RestartPolicy   RestartPolicy // Restart policy to be used for the container
	AutoRemove      bool          // Automatically remove container when it exits
	VolumeDriver    string        // Name of the volume driver used to mount volumes
	VolumesFrom     []string      // List of volumes to take from other container

	// Applicable to UNIX platforms
	CapAdd          strslice.StrSlice // List of kernel capabilities to add to the container
	CapDrop         strslice.StrSlice // List of kernel capabilities to remove from the container
	DNS             []string          `json:"Dns"`        // List of DNS server to lookup
	DNSOptions      []string          `json:"DnsOptions"` // List of DNSOption to look for
	DNSSearch       []string          `json:"DnsSearch"`  // List of DNSSearch to look for
	ExtraHosts      []string          // List of extra hosts
	GroupAdd        []string          // List of additional groups that the container process will run as
	IpcMode         IpcMode           // IPC namespace to use for the container
	Cgroup          CgroupSpec        // Cgroup to use for the container
	Links           []string          // List of links (in the name:alias form)
	OomScoreAdj     int               // Container preference for OOM-killing
	PidMode         PidMode           // PID namespace to use for the container
	Privileged      bool              // Is the container in privileged mode
	PublishAllPorts bool              // Should docker publish all exposed port for the container
	ReadonlyRootfs  bool              // Is the container root filesystem in read-only
	SecurityOpt     []string          // List of string values to customize labels for MLS systems, such as SELinux.
	StorageOpt      map[string]string `json:",omitempty"` // Storage driver options per container.
	Tmpfs           map[string]string `json:",omitempty"` // List of tmpfs (mounts) used for the container
	UTSMode         UTSMode           // UTS namespace to use for the container
	UsernsMode      UsernsMode        // The user namespace to use for the container
	ShmSize         int64             // Total shm memory usage
	Sysctls         map[string]string `json:",omitempty"` // List of Namespaced sysctls used for the container
	Runtime         string            `json:",omitempty"` // Runtime to use with this container

	// Applicable to Windows
	ConsoleSize [2]uint   // Initial console size (height,width)
	Isolation   Isolation // Isolation technology of the container (e.g. default, hyperv)

	// Contains container's resources (cgroups, ulimits)
	Resources

	// Mounts specs used by the container
	Mounts []mount.Mount `json:",omitempty"`

	// Run a custom init inside the container, if null, use the daemon's configured settings
	Init *bool `json:",omitempty"`

	// Custom init path
	InitPath string `json:",omitempty"`
}

**Comment by athrane** [comment]
To align schema names with docker types:
Rename InspectedContainer to ContainerJSONBase 
Rename InspectedContainerHostConfig to HostConfig
